### ISSUE TITLE
breaks help command

### ISSUE THREAD

**Issue by Moistcrafter** [ffauzan/gc-equip#1]
03:02:15 <ERROR:Grasscutter> Command error:
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] emu.grasscutter.command.Command.usage() (Found data of type java.lang.String[equip <weaponId>])
        at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:59)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
        at jdk.proxy2/jdk.proxy2.$Proxy6.usage(Unknown Source)
        at emu.grasscutter.command.CommandHandler.getUsageString(CommandHandler.java:58)
        at emu.grasscutter.command.commands.HelpCommand.createCommand(HelpCommand.java:22)
        at emu.grasscutter.command.commands.HelpCommand.lambda$execute$0(HelpCommand.java:56)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
        at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:53)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:302)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:166)
>

**Comment by ffauzan** [comment]
> 03:02:15 ERROR:Grasscutter Command error: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] emu.grasscutter.command.Command.usage() (Found data of type java.lang.String[equip ]) at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:59) at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89) at jdk.proxy2/jdk.proxy2.$Proxy6.usage(Unknown Source) at emu.grasscutter.command.CommandHandler.getUsageString(CommandHandler.java:58) at emu.grasscutter.command.commands.HelpCommand.createCommand(HelpCommand.java:22) at emu.grasscutter.command.commands.HelpCommand.lambda$execute$0(HelpCommand.java:56) at java.base/java.util.TreeMap.forEach(TreeMap.java:1282) at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:53) at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310) at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314) at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:302) at emu.grasscutter.Grasscutter.main(Grasscutter.java:166)
> 
> >

I'll take a look at this after installing the game. It's been a long time since I update this plugin.

**Comment by ffauzan** [comment]
> 03:02:15 ERROR:Grasscutter Command error: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] emu.grasscutter.command.Command.usage() (Found data of type java.lang.String[equip ]) at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:59) at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89) at jdk.proxy2/jdk.proxy2.$Proxy6.usage(Unknown Source) at emu.grasscutter.command.CommandHandler.getUsageString(CommandHandler.java:58) at emu.grasscutter.command.commands.HelpCommand.createCommand(HelpCommand.java:22) at emu.grasscutter.command.commands.HelpCommand.lambda$execute$0(HelpCommand.java:56) at java.base/java.util.TreeMap.forEach(TreeMap.java:1282) at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:53) at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310) at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314) at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:302) at emu.grasscutter.Grasscutter.main(Grasscutter.java:166)
> 
> >

Checkout the new release version, it should fix this problem
[v1.0.1](https://github.com/ffauzan/gc-equip/releases/tag/v1.0.1)
